### ISSUE TITLE
Use systemd-resolved dbus interface instead of creating *.network files on-the-fly

### ISSUE THREAD

**Issue by piotr-dobrogost** [masterkorp/openvpn-update-resolv-conf#13]
Currently, [`update-systemd-network.sh`](https://github.com/WGH-/openvpn-update-resolv-conf/blob/91d2ec0a52f9ea4fb1a62d79a98d7c48bf198bf7/update-systemd-network.sh) script creates `.network` files and restarts `systemd-networkd`. I asked on #systemd if this is the right way of doing this and got response from @grawity:

> the proper way to make it work is to call org.freedesktop.resolve1.Manager.SetLinkDNS() via DBus

When using dbus there's no need to restart any service and create any files.
Docs for dbus API of resolved are at https://www.freedesktop.org/wiki/Software/systemd/resolved/

Compare [RFE: please consider pushing DNS information into systemd-resolved](https://bugzilla.gnome.org/show_bug.cgi?id=762540)

cc @WGH-

**Comment by WGH-** [comment]
However, if systemd-networkd is restarted for any reason, it'll lose all the info. The solution with temporary .network files doesn't have this problem.

**Comment by piotr-dobrogost** [comment]
I don't know systemd very well but I don't see how restarting networkd would make other service (resolved) loose any info.

**Comment by poettering** [comment]
The best option would be to push the DNS data directly into resolved, as mentioned. 

Restarting networkd has no effect on resolved keeping the DNS data you pushed into it around or not. However, currently resolved will forget data you push into it if you restart resolved itself. That's certainly something we should fix though... I added that to my todo list now.

It would be fantastic if openvpn would push its discovered DNS data directly into resolved via the API we provide, and we have prepped documentation explaining how to do this:

https://wiki.freedesktop.org/www/Software/systemd/writing-network-configuration-managers/

Note that the interfaces have been added very recently only, hence you need 229 or newer to make this work.

**Comment by WGH-** [comment]
Also, it seems that implemented solution is broken on newer systemd. Restarting systemd-networkd removes the IP from the interface for some reason.

**Comment by WGH-** [comment]
https://github.com/jonathanio/update-systemd-resolved
This script seems to do the job. I don't really feel like rewriting what already works fine :)

**Comment by piotr-dobrogost** [comment]
Thanks for you engagement in this and the link!
Maybe `update-systemd-network.sh` script should be dropped then and information about https://github.com/jonathanio/update-systemd-resolved added to readme instead?

**Comment by WGH-** [comment]
The script might remain useful for distributions stuck with older systemd versions, like Debian Jessie or Gentoo stable, though. So I'm against the complete removal.

But users running newer systemd should be redirected to the better script, I think.
