### ISSUE TITLE
Solves domain name resolution data leakage?

### ISSUE THREAD

**Issue by TheNotary** [masterkorp/openvpn-update-resolv-conf#3]
Hey, thanks for uploading this.  Just to clarify, this solves DNS resolution so domain names cannot be resolved through your ISP's DNS?  

Also, do you know a way of testing that this is working?

**Comment by masterkorp** [comment]
Hello  @TheNotary 
Depending on the situation this can or it cannot solve that problem. All this script does it to update the DNS entries on your ``/etc/resolv.conf`` file.

If you want to hide the DNS request from your ISP, you will need to have a DNS server inside the network you are connecting to, and all the DNS queries will go to that server.
To test you can use the dig command once you're connected:

```
$ dig -x google.com    

; <<>> DiG 9.10.3 <<>> -x google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15496
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;com.google.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
in-addr.arpa.		60	IN	SOA	b.in-addr-servers.arpa. nstld.iana.org. 2015072365 1800 900 604800 3600

;; Query time: 119 msec
;; SERVER: 123.456.123.789#53(172.31.9.199)
;; WHEN: Mon Nov 16 16:24:56 WET 2015
;; MSG SIZE  rcvd: 12
```
The ``SERVER`` section tells you the IP address of the DNS server that responded to your request. If the IP is from a server on the network inside the network, your ISP won't get that query.

Hope this helps.

**Comment by TheNotary** [comment]
Thanks for this answer, it's greatly appreciated =)

**Comment by masterkorp** [comment]
I will close this issue. Reopen if you any more questions.
