### ISSUE TITLE
DNS leaks

### ISSUE THREAD

**Issue by Ptolom** [masterkorp/openvpn-update-resolv-conf#5]
This script is causing DNS leaks.

`echo -n "$R" | $RESOLVCONF -a "${dev}.inet"`
Does not remove the old DNS servers from resolv.conf. 

Adding the exclusive flag (-x) to resolvconf will stop the old DNS from being used.
`echo -n "$R" | $RESOLVCONF -a -x "${dev}.inet"`

**Comment by masterkorp** [comment]
Hello @Ptolom 
What are the drawbacks of using `-x` for the other DNS servers?

**Comment by masterkorp** [comment]
Nevermind my previous comment. Just re-read the issue.
